---
title: "Making streamgraphs in R"
description: |
  TidyTuesday May 03,2022 ; Power and Energy Capacity visualization.
author:
  - name: Karat Sidhu
    url: {}
date: 2022-05-03
categories:
  - TidyTuesday
  - Data-Viz
  - TidyVerse
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

TidyTuesday Dataset for Week of May 03, 2022. The dataset featured the hidden gems files from Berkeley Lab/Dept of Energy.

## Loading Libraries

```{r}
library(ggstream)
library(tidyverse)
library(patchwork)
library(showtext)
showtext_opts(dpi = 450)
showtext_auto(enable = TRUE)
library(ggtext)
font_add_google(family = "Bangers", name = "Bangers")

```

## Loading and cleaning Data

```{r}
capacity <-
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-03/capacity.csv'
  )
wind <-
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-03/wind.csv'
  )
solar <-
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-03/solar.csv'
  )
average_cost <-
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-03/average_cost.csv'
  )
capacity <- capacity %>%
  mutate(across(where(anyNA), ~ replace_na(., 0)))
capacity <- capacity %>%
  mutate(prior = standalone_prior + hybrid_prior) %>%
  mutate(new = standalone_new + hybrid_new)

```


## Making the plot

```{r}
colors_legend <- c("#FFB327",
                   "#D1F1F9",
                   "#4F607C",
                   "#c5b689",
                   "#8E038E",
                   "#5A6D87",
                   "#000000")
plot1 <- ggplot(capacity, aes(year, prior, fill = type)) +
  geom_stream(
    extra_span = .25,
    true_range = "none",
    bw = .85,
    size = 1.25,
    sorting = "onset"
  ) +
  geom_stream(
    geom = "contour",
    color = "white",
    extra_span = .25,
    true_range = "none",
    bw = .85,
    size = 0.09,
    sorting = "onset"
  ) +
  scale_fill_manual(values = colors_legend,
                    name = NULL) +
  scale_x_continuous(breaks = c(2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020)) +
  theme_minimal(base_family = "Bangers") +
  theme(
    plot.background = element_rect(fill = "grey84", color = NA),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    legend.position = "bottom",
    legend.text = element_text(color = "grey40", size = 14),
    legend.box.margin = margin(t = 30),
    legend.background = element_rect(color = "grey40",
                                     size = .3,
                                     fill = "grey95"),
    legend.key.height = unit(.25, "lines"),
    legend.key.width = unit(2.5, "lines"),
    plot.margin = margin(rep(20, 4))
  ) +
  labs(title = "Prior Generation Capacity (Gigawatts)") +
  theme(plot.title = element_text(hjust = 0.5))
plot1
plot2 <- ggplot(capacity, aes(year, new, fill = type)) +
  geom_stream(
    extra_span = .25,
    true_range = "none",
    bw = .85,
    size = 1.25,
    sorting = "onset"
  ) +
  geom_stream(
    geom = "contour",
    color = "white",
    extra_span = .25,
    true_range = "none",
    bw = .85,
    size = 0.02,
    sorting = "onset"
  ) +
  scale_fill_manual(values = colors_legend,
                    name = NULL) +
  scale_x_continuous(breaks = c(2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020)) +
  theme_minimal(base_family = "Bangers") +
  theme(
    plot.background = element_rect(fill = "grey84", color = NA),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    legend.position = "none",
    plot.margin = margin(rep(20, 4))
  ) +
  labs(title = "New Generation Capacity (Gigawatts)") +
  theme(plot.title = element_text(hjust = 0.5))
plot_final <- plot1 / plot2 +
  plot_annotation(
    title = 'Power Generation Capacity',
    subtitle = 'The shreamcharts describe the power generation from various sources (solar, nuclear, wind, etc) along with <br>
    their capacity over the years. The graphs are separated into New and Prior Generation <br> In Gigawatts. <br> ',
    caption = 'Data: Berkeley Lab | Graphic: Github.com/SidhuK ',
    theme = theme(
      plot.title = element_text(size = 35, hjust = 0.5),
      plot.subtitle = element_markdown(size = 15, hjust = 0.5),
      plot.caption = element_text(size = 11, hjust = 0.5),
      plot.background = element_rect(fill = "grey84", color = NA)
    )
  ) &
  theme(text = element_text('Bangers'))


```


```{r fig.height=10, fig.width=8 }
plot_final


```


### Visit my TidyTuesday Repo for a better look.

